spring:
  application:
    name: BackendDeployService

  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect

app:
  base-domain: ${BASE_DOMAIN}

  aws:
    region: ${AWS_REGION}
    ecs:
      cluster-name: ${AWS_ECS_CLUSTER_NAME}
      security-group: ${AWS_SECURITY_GROUP}
      subnet-1: ${AWS_SUBNET_1}
      subnet-2: ${AWS_SUBNET_2}
